services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vault
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
          - ./init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
  backend:
    build: ./cubbit-be
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    links:
      - mysql